ktor {
    application {
        modules = [com.timothymarias.shoppinglist.server.ApplicationKt.module]
    }
    deployment {
        port = 8080
        host = 0.0.0.0
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/shoppinglist"
    user = "shoppinglist"
    password = "changeme"
    maxPoolSize = 5
}
